begin;
create extension if not exists pgtap with schema extensions;
select plan(11);
delete from vault.secrets where name = 'waldo_router_hmac';
select vault.create_secret('test-router-secret', 'waldo_router_hmac');
create function pg_temp.at() returns bigint language sql as $$ select extract(epoch from now())::bigint $$;
create function pg_temp.sig(msg text) returns text language sql as $$ select encode(extensions.hmac(pg_temp.at()::text || '.' || msg, 'test-router-secret', 'sha256'), 'hex') $$;
insert into waldo.owners (do_name, email) values ('do-a', 'a@test.invalid'), ('do-b', 'b@test.invalid');
select is(has_function_privilege('anon', 'waldo.proxy_secret(text, uuid)', 'execute'), false, 'the runtime key cannot read a token');
select is(has_function_privilege('anon', 'waldo.proxy_store(text, text, text, text, text)', 'execute'), false, 'the runtime key cannot store a token');
create temp table c as select waldo.proxy_store('do-a', 'google', 'Work@x.test', 'calendar', 'rt-1') as id;
select is((select count(*)::int from waldo.connections where secret_id in (select id from vault.secrets)), 1, 'the token sits in Vault');
select is((select count(*)::int from waldo.connections c join vault.secrets s on s.id = c.secret_id where s.secret = 'rt-1'), 0, 'Vault holds it encrypted');
select is(waldo.proxy_secret('do-a', (select id from c)), 'rt-1', 'the proxy reads the owner token');
select is(waldo.proxy_secret('do-b', (select id from c)), null, 'another owner name reads nothing');
select is(waldo.proxy_store('do-a', 'google', 'work@x.test', 'calendar gmail.send', 'rt-2'), (select id from c), 'reconnecting the same account updates it in place');
select is(waldo.proxy_health('do-a', (select id from c), 'invalid_grant'), true, 'a refresh failure is recorded');
select is(waldo.connection_list('do-a', pg_temp.at(), pg_temp.sig('connlist.do-a'))->0->>'status', 'failing', 'the health row shows it failing');
select is(waldo.connection_revoke('do-a', (select id from c), pg_temp.at(), pg_temp.sig('connrevoke.do-a.' || (select id from c))), true, 'the owner revokes the connection');
select is((select count(*)::int from vault.secrets s join waldo.connections c2 on c2.secret_id = s.id), 0, 'revoking deletes the Vault secret');
select * from finish();
rollback;
