begin;
create extension if not exists pgtap with schema extensions;
select plan(11);
select vault.create_secret('test-router-secret', 'waldo_router_hmac');
create function pg_temp.at() returns bigint language sql as $$ select extract(epoch from now())::bigint $$;
create function pg_temp.sig(msg text) returns text language sql as $$ select encode(extensions.hmac(pg_temp.at()::text || '.' || msg, 'test-router-secret', 'sha256'), 'hex') $$;
create function pg_temp.h(t text) returns text language sql as $$ select encode(extensions.digest(t, 'sha256'), 'hex') $$;
insert into waldo.owners (do_name, email) values ('do-a', 'a@test.invalid'), ('do-b', 'b@test.invalid');
create temp table c as select waldo.connection_store('do-a', 'google', 'Work@x.test', 'calendar', 'rt-1', pg_temp.at(), pg_temp.sig('connstore.do-a.google.work@x.test.calendar.' || pg_temp.h('rt-1'))) as id;
select isnt((select id from c), null, 'a connection is stored');
select is((select count(*)::int from waldo.connections where secret_id in (select id from vault.secrets)), 1, 'the token sits in Vault');
select is((select count(*)::int from waldo.connections c join vault.secrets s on s.id = c.secret_id where s.secret = 'rt-1'), 0, 'Vault holds it encrypted');
select throws_ok($$ select waldo.connection_store('do-a', 'google', 'work@x.test', 'calendar', 'rt-evil', pg_temp.at(), pg_temp.sig('connstore.do-a.google.work@x.test.calendar.' || pg_temp.h('rt-1'))) $$, '42501', 'unsigned router call', 'a signature for one token cannot store another');
select is(waldo.connection_secret('do-a', (select id from c), pg_temp.at(), pg_temp.sig('connsecret.do-a.' || (select id from c))), 'rt-1', 'the owner reads its token back');
select is(waldo.connection_secret('do-b', (select id from c), pg_temp.at(), pg_temp.sig('connsecret.do-b.' || (select id from c))), null, 'another owner cannot read it');
select is(waldo.connection_store('do-a', 'google', 'work@x.test', 'calendar gmail.send', 'rt-2', pg_temp.at(), pg_temp.sig('connstore.do-a.google.work@x.test.calendar gmail.send.' || pg_temp.h('rt-2'))), (select id from c), 'reconnecting the same account updates it in place');
select is(waldo.connection_health('do-a', (select id from c), 'invalid_grant', pg_temp.at(), pg_temp.sig('connhealth.do-a.' || (select id from c) || '.invalid_grant')), true, 'a refresh failure is recorded');
select is(waldo.connection_list('do-a', pg_temp.at(), pg_temp.sig('connlist.do-a'))->0->>'status', 'failing', 'the health row shows it failing');
select is(waldo.connection_revoke('do-a', (select id from c), pg_temp.at(), pg_temp.sig('connrevoke.do-a.' || (select id from c))), true, 'the owner revokes the connection');
select is((select count(*)::int from vault.secrets s join waldo.connections c2 on c2.secret_id = s.id), 0, 'revoking deletes the Vault secret');
select * from finish();
rollback;
