begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
delete from vault.secrets where name = 'waldo_router_hmac';
select vault.create_secret('test-router-secret', 'waldo_router_hmac');
create function pg_temp.at() returns bigint language sql as $$ select extract(epoch from now())::bigint $$;
create function pg_temp.sig(msg text) returns text language sql as $$ select encode(extensions.hmac(pg_temp.at()::text || '.' || msg, 'test-router-secret', 'sha256'), 'hex') $$;
create function pg_temp.issue(o text, h text) returns boolean language sql as $$ select waldo.issue_device_pairing_code(o,h,pg_temp.at(),pg_temp.sig('devpair.'||o||'.'||h)) $$;
create function pg_temp.redeem(h text, k text, l text default 'Test Mac', c text default 'machine_state_query') returns table(device_id text, owner_id text) language sql as $$ select * from waldo.redeem_device_pairing(h,k,l,c,pg_temp.at(),pg_temp.sig('devredeem.'||h||'.'||k||'.'||encode(convert_to(l,'UTF8'),'hex')||'.'||c)) $$;
create function pg_temp.throttle(k text, lim int, win int) returns boolean language sql as $$ select waldo.device_bridge_throttle(k,lim,win,pg_temp.at(),pg_temp.sig('devthrottle.'||k||'.'||lim||'.'||win)) $$;
insert into waldo.owners(do_name,email) values ('bridge-a','bridge-a@test.invalid'),('bridge-b','bridge-b@test.invalid'),('bridge-cap','bridge-cap@test.invalid');
select throws_ok($$select waldo.issue_device_pairing_code('bridge-a',repeat('a',64),pg_temp.at(),'forged')$$,'42501','unsigned router call','forged mint refused');
select is(pg_temp.issue('bridge-a',repeat('a',64)),true,'mint');
select is(pg_temp.issue('bridge-b',repeat('a',64)),false,'hash collision never overwrites');
select throws_ok($$select waldo.redeem_device_pairing(repeat('a',64),repeat('A',43),'changed','machine_state_query',pg_temp.at(),pg_temp.sig('devredeem.'||repeat('a',64)||'.'||repeat('A',43)||'.'||encode(convert_to('Test Mac','UTF8'),'hex')||'.machine_state_query'))$$,'42501','unsigned router call','label tampering rejected');
select throws_ok($$select waldo.redeem_device_pairing(repeat('a',64),repeat('A',43),'Test Mac','notify_local',pg_temp.at(),pg_temp.sig('devredeem.'||repeat('a',64)||'.'||repeat('A',43)||'.'||encode(convert_to('Test Mac','UTF8'),'hex')||'.machine_state_query'))$$,'42501','unsigned router call','capability tampering rejected');
create temp table paired as select * from pg_temp.redeem(repeat('a',64),repeat('A',43));
select is((select count(*)::int from paired),1,'one redemption');
select is((select count(*)::int from pg_temp.redeem(repeat('a',64),repeat('B',43))),0,'used code refused');
select is((select count(*)::int from pg_temp.redeem(repeat('9',64),repeat('B',43))),0,'unknown code refused');
select pg_temp.issue('bridge-a',repeat('b',64));
update waldo.device_pairing_codes set created_at=now()-interval '600 seconds',expires_at=now() where code_hash=repeat('b',64);
select is((select count(*)::int from pg_temp.redeem(repeat('b',64),repeat('B',43))),0,'exact expiry boundary refused');
update waldo.device_pairing_codes set created_at=now()-interval '599 seconds',expires_at=now()+interval '1 second' where code_hash=repeat('b',64);
select is((select count(*)::int from pg_temp.redeem(repeat('b',64),repeat('A',43))),0,'public-key collision returns no rows');
select ok((select used_at is null from waldo.device_pairing_codes where code_hash=repeat('b',64)),'key collision rolls back code use');
select is((select count(*)::int from pg_temp.redeem(repeat('b',64),repeat('B',43))),1,'one second before expiry accepted');
select is((select count(*)::int from waldo.list_devices('bridge-b',pg_temp.at(),pg_temp.sig('devlist.bridge-b'))),0,'list scoped to owner');
select is(waldo.revoke_device('bridge-b',(select device_id from paired),pg_temp.at(),pg_temp.sig('devrevoke.bridge-b.'||(select device_id from paired))),false,'cross-owner revoke refused');
select is((select count(*)::int from waldo.device_for_auth((select device_id from paired),pg_temp.at(),pg_temp.sig('devauth.'||(select device_id from paired)))),1,'other owner device retained');
update waldo.owners set state='suspended' where do_name='bridge-a';
select is((select count(*)::int from waldo.device_for_auth((select device_id from paired),pg_temp.at(),pg_temp.sig('devauth.'||(select device_id from paired)))),0,'suspended owner cannot authenticate');
select is(waldo.device_touch((select device_id from paired),pg_temp.at(),pg_temp.sig('devtouch.'||(select device_id from paired))),false,'suspended owner cannot touch');
select is(pg_temp.issue('bridge-a',repeat('c',64)),false,'suspended owner cannot mint');
update waldo.owners set state='active' where do_name='bridge-a';
select is(waldo.revoke_device('bridge-a',(select device_id from paired),pg_temp.at(),pg_temp.sig('devrevoke.bridge-a.'||(select device_id from paired))),true,'owner revokes');
select is((select count(*)::int from waldo.device_for_auth((select device_id from paired),pg_temp.at(),pg_temp.sig('devauth.'||(select device_id from paired)))),0,'revoked device cannot authenticate');
select is((select count(*)::int from waldo.device_for_auth('unknown',pg_temp.at(),pg_temp.sig('devauth.unknown'))),0,'unknown device cannot authenticate');
select ok(bool_and(pg_temp.issue('bridge-cap',lpad(n::text,64,'0'))),'first five codes admitted') from generate_series(1,5) n;
select is(pg_temp.issue('bridge-cap',lpad('6',64,'0')),false,'sixth outstanding code refused');
select ok(bool_and(pg_temp.throttle('devredeem.ip60.'||repeat('1',64),5,60)),'first five attempts admitted') from generate_series(1,5);
select is(pg_temp.throttle('devredeem.ip60.'||repeat('1',64),5,60),false,'sixth attempt denied');
select pg_temp.throttle('devredeem.ip3600.'||repeat('1',64),20,3600);
select is(pg_temp.throttle('devredeem.ip60.'||repeat('1',64),5,60),false,'hour throttle never cleans minute throttle');
update waldo.device_bridge_throttle_keys set admitted_at=array[now()-interval '60 seconds'] where key='devredeem.ip60.'||repeat('1',64);
select is(pg_temp.throttle('devredeem.ip60.'||repeat('1',64),5,60),true,'exact rolling boundary expires old attempt');
select throws_ok($$select pg_temp.throttle('devredeem.ip60.'||repeat('1',64),500,60)$$,'22023','invalid device throttle profile','signed caller cannot widen throttle profile');
select is((select count(*)::int from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='waldo' and c.relname in ('devices','device_pairing_codes','device_bridge_throttle_keys') and c.relrowsecurity and c.relforcerowsecurity),3,'all tables force RLS');
select ok(not has_table_privilege('anon','waldo.devices','SELECT'),'anon cannot directly read devices');
select ok(not has_table_privilege('authenticated','waldo.device_pairing_codes','SELECT'),'authenticated cannot read pairing hashes');
select is(waldo.delete_owner('bridge-a',pg_temp.at(),pg_temp.sig('delown.bridge-a')),true,'delete owner succeeds');
select is((select count(*)::int from waldo.devices d join waldo.owners o on o.id=d.owner_id where o.do_name='bridge-a'),0,'owner devices removed');
select is((select count(*)::int from waldo.device_pairing_codes where code_hash in (repeat('a',64),repeat('b',64))),0,'owner pairing codes cascade');
select * from finish();
rollback;
