import { useEffect, useState } from 'react';
import type { OverviewV1 } from './model';
import { fetchOverview } from './model';
import './style.css';

type Route = 'overview' | 'waiting' | 'patrol' | 'memory' | 'connections';
const routes: readonly { key: Route; label: string }[] = [
  { key: 'overview', label: 'Overview' }, { key: 'waiting', label: 'Waiting' }, { key: 'patrol', label: 'Patrol' },
  { key: 'memory', label: 'Memory' }, { key: 'connections', label: 'Connections' },
];
const validRoute = (value: string): Route => routes.find((r) => r.key === value)?.key ?? 'overview';
const currentRoute = () => validRoute(window.location.hash.replace(/^#\/?/, ''));
const date = (iso: string, zone: string) => {
  try { return new Intl.DateTimeFormat('en', { timeZone: zone, dateStyle: 'medium', timeStyle: 'short' }).format(new Date(iso)); }
  catch { return 'Time unavailable'; }
};
const Section = ({ eyebrow, title, children }: { eyebrow: string; title: string; children: React.ReactNode }) => <section className="panel"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{children}</section>;
export function Dashboard({ data, route }: { data: OverviewV1; route: Route }) {
  if (route === 'waiting') return <><div className="page-heading"><span className="eyebrow">Needs your judgment</span><h1>Waiting.</h1><p>Proposed work is not a completed action.</p></div><Section eyebrow="Pending" title={`${data.waiting.count} ${data.waiting.count === 1 ? 'decision' : 'decisions'}`}><p>{data.waiting.first?.summary ?? 'Nothing is waiting for a decision right now.'}</p><p className="muted">Full recipient, content and effect review is required before any approval. This read-only view cannot approve a change.</p></Section></>;
  if (route === 'patrol') return <><div className="page-heading"><span className="eyebrow">Recorded work</span><h1>Patrol.</h1><p>Only completed records, not inferred progress.</p></div><Section eyebrow="Latest recorded activity" title={data.latest_activity?.kind ?? 'No activity recorded'}><p>{data.latest_activity?.summary ?? 'No activity record is available yet.'}</p>{data.latest_activity && <p className="muted">{data.latest_activity.status} · {date(data.latest_activity.at, data.timezone)}</p>}</Section></>;
  if (route === 'memory') return <><div className="page-heading"><span className="eyebrow">Your context</span><h1>Memory.</h1></div><Section eyebrow="Not connected to this read contract" title="No memory details here yet."><p>The first read-only dashboard contract does not expose memory claims. The existing owner console remains the place to inspect evidence notes and request a correction or forget action.</p><p className="muted">No claim is displayed without its provenance and correction path.</p></Section></>;
  if (route === 'connections') return <><div className="page-heading"><span className="eyebrow">Connected accounts</span><h1>Connections.</h1><p>A saved grant is not a successful live read.</p></div><div className="stack">{data.services.length ? data.services.map((service) => <Section key={service.account_id} eyebrow={service.health === 'needs_reconnect' ? 'Reconnect needed' : 'Access granted · read unverified'} title={service.email}><p>{service.grants.length ? service.grants.join(' · ') : 'No active grants'}</p></Section>) : <Section eyebrow="No active connections" title="Nothing connected yet."><p>Connect an account when Waldo needs it for a task. This dashboard does not assume a tool has worked.</p></Section>}</div></>;
  const brief = data.brief.status === 'sent_recorded' ? 'The Brief is marked sent.' : data.brief.status === 'not_scheduled' ? 'No Brief is scheduled.' : 'The Brief has not been sent.';
  return <><div className="hero"><div><span className="eyebrow">Your Waldo · {date(data.as_of, data.timezone)}</span><h1>Here is where<br/><em>things stand.</em></h1><p>What needs you, what ran, and what comes next. No guesswork.</p></div><span className="state-pill">{data.waiting.count} waiting on you</span></div><div className="overview-grid"><Section eyebrow="The Brief" title={brief}><p>{data.brief.status === 'sent_recorded' ? 'Waldo recorded a send. This does not confirm delivery or show message text; open your chat to check.' : 'No Brief content is available here.'}</p>{data.brief.at && <p className="muted">Recorded {date(data.brief.at, data.timezone)}</p>}</Section><div className="stack"><Section eyebrow="The handoff" title={data.waiting.count ? `${data.waiting.count} ${data.waiting.count === 1 ? 'decision' : 'decisions'} waiting.` : 'Nothing waiting.'}><p>{data.waiting.first?.summary ?? 'No decision is waiting for you right now.'}</p><a href="#/waiting">Review what's waiting →</a></Section><Section eyebrow="Next on the day" title={data.next_card?.label ?? 'No card scheduled ahead.'}><p>{data.next_card ? date(data.next_card.scheduled_at, data.timezone) : 'No future card is recorded in this plan.'}</p></Section></div></div><div className="latest"><span className="eyebrow">Latest recorded activity</span><p>{data.latest_activity ? `${data.latest_activity.kind} · ${data.latest_activity.status} · ${date(data.latest_activity.at, data.timezone)}` : 'No activity record available yet.'}</p></div></>;
}
export function App() {
  const [route, setRoute] = useState<Route>(currentRoute);
  const [state, setState] = useState<{ kind: 'loading' } | { kind: 'ready'; data: OverviewV1 } | { kind: 'error'; message: string }>({ kind: 'loading' });
  const [retry, setRetry] = useState(0);
  useEffect(() => { const onHash = () => setRoute(currentRoute()); window.addEventListener('hashchange', onHash); return () => window.removeEventListener('hashchange', onHash); }, []);
  useEffect(() => { const controller = new AbortController(); setState({ kind: 'loading' }); fetchOverview(controller.signal).then((data) => { if (!controller.signal.aborted) setState({ kind: 'ready', data }); }).catch((error: unknown) => { if (!controller.signal.aborted) setState({ kind: 'error', message: error instanceof Error ? error.message : 'The dashboard could not load right now.' }); }); return () => controller.abort(); }, [retry]);
  return <div className="frame"><header><a className="brand" href="#/overview" aria-label="Waldo dashboard home">Waldo <small>Dashboard</small></a><span className="header-status">Your day, honestly.</span></header><nav aria-label="Dashboard pages">{routes.map((item) => <a aria-current={route === item.key ? 'page' : undefined} key={item.key} href={`#/${item.key}`}>{item.label}</a>)}</nav><main id="main">{state.kind === 'loading' ? <div role="status" className="feedback">Checking what has been recorded…</div> : state.kind === 'error' ? <div role="alert" className="feedback"><h1>Not available yet.</h1><p>{state.message}</p><button onClick={() => setRetry((n) => n + 1)}>Try again</button></div> : <Dashboard data={state.data} route={route}/>}</main><footer>Only confirmed records belong here. An action is not done until its result is checked.</footer></div>;
}
