import{describe,it,expect}from'vitest';
import{renderArtifactBody,telegramRichReply}from'../src/channels/rich-format';
describe('inert artifact rich rendering',()=>{
 it('renders document headings and read-only checklist without active controls',()=>{const h=renderArtifactBody('document','# Reset\n\n- [ ] Water\n- [x] Done\n\n**Easy** movement');expect(h).toContain('<h2>Reset</h2>');expect(h).toContain('☐ Water');expect(h).toContain('☑ Done');expect(h).toContain('<strong>Easy</strong>');expect(h).not.toContain('<input');});
 it('escapes raw HTML and link schemes instead of interpreting body-derived active content',()=>{const h=renderArtifactBody('document','<script>alert(1)</script>\n<img src=x onerror=x>\n[bad](javascript:alert(1))\n[remote](https://evil.invalid)');expect(h).not.toMatch(/<(script|img|a|iframe|svg|style)\b/);expect(h).toContain('&#60;script');expect(h).toContain('javascript:');});
 it('data artifacts remain literal; fenced Markdown code is escaped',()=>{expect(renderArtifactBody('data','# hi\n<script>x</script>')).toContain('<pre>');expect(renderArtifactBody('data','# hi')).not.toContain('<h2>');expect(renderArtifactBody('document','```html\n<img src=x>\n```')).toContain('<pre><code>&#60;img');});
});
describe('Telegram final formatting after link guard',()=>{
 it('formats an existing exact HTTP link using escaped HTML, never expands URLs',()=>{const url='https://staging.invalid/console/artifacts/art%3Atest?revision=1&v=2';const r=telegramRichReply(`Made [Open the private file](${url}) <script>x</script>`);expect(r.parse_mode).toBe('HTML');expect(r.text).toContain(`<a href="https://staging.invalid/console/artifacts/art%3Atest?revision=1&#38;v=2">Open the private file</a>`);expect(r.text).toContain('&#60;script');});
 it('never activates non-http schemes or raw model HTML',()=>{const r=telegramRichReply('[x](javascript:alert(1)) <a href="https://evil.invalid">evil</a>');expect(r.text).not.toContain('<a ');expect(r.text).toContain('&#60;a');});
 it('uses literal escaped text for malformed markdown',()=>{expect(telegramRichReply('[broken](https://').text).toContain('[broken]');});
});
import{createTelegramOwnerApi}from'../src/channels/telegram-api';
it('table/image/HTML instructions cannot create network-active artifact nodes',()=>{for(const payload of ['![pixel](https://evil.invalid/collect)','<svg onload=alert(1)>','<style>body{background:url(https://evil.invalid)}</style>','<iframe srcdoc="<script>x</script>">','[x](data:text/html,x)','<form action="https://evil.invalid">']){expect(renderArtifactBody('research',payload)).not.toMatch(/<(img|svg|script|style|iframe|form|a)\b/);}});

import{TelegramOwnerListener}from'../src/channels/telegram-listener';
import{guardArtifactLinks,receiptUrl}from'../src/conversation/artifact-link-guard';
it('owner final reply guard and formatter work together; direct sends remain literal',async()=>{const sent:unknown[]=[];const api=createTelegramOwnerApi(async(method,body)=>{if(method==='sendMessage'){sent.push(body);return {message_id:1};}});const url='https://staging.invalid/console/artifacts/art%3Atest?revision=1';const receipt=receiptUrl('create_artifact',{ok:true,source_taint:null,data:{delivery:{status:'owner_link',audience:'owner_authenticated',url}}});const listener=new TelegramOwnerListener({ownerTelegramId:12,api,respond:async()=>guardArtifactLinks(`[File](${url}) [Invented](https://staging.invalid/art:invented)`,new Set([receipt!])),saveOffset:async()=>undefined});await listener.handle({updateId:1,messageId:2,senderId:12,chatId:12,sentAt:null,text:'make a file'});expect(sent[0]).toMatchObject({chat_id:12,parse_mode:'HTML'});expect((sent[0]as{text:string}).text).toContain(`<a href="${url}">File</a>`);expect((sent[0]as{text:string}).text).not.toContain('https://staging.invalid/art:invented');await api.sendMessage({chat_id:12,text:'Event: [outside](https://evil.invalid)'});expect(sent[1]).toEqual({chat_id:12,text:'Event: [outside](https://evil.invalid)'});});
