import {describe,it,expect} from 'vitest';
import {projectMemoryControl,memoryControl,resolveMemoryAction} from '../src/channels/dashboard-memory-actions';
import {controlRevision} from '../src/channels/dashboard-control-actions';
import {SAMPLE_CONSOLE_VIEW} from './fixtures/console-sample';
describe('owner Memory action resolution',()=>{
 it('requires an exact owner-scoped authoritative target, never numeric or foreign-owner IDs',()=>{for(const id of ['5','other:claim:5','owner:claim:999','owner:node:5'])expect(resolveMemoryAction(SAMPLE_CONSOLE_VIEW,'owner',{action:'spot.confirm',id,value:''})).toBeNull();expect(resolveMemoryAction(SAMPLE_CONSOLE_VIEW,'owner',{action:'spot.confirm',id:'owner:claim:5',value:''})?.id).toBe('5');});
 it('preserves confirm only for inferred active Spots and incomplete forget retry only',()=>{expect(memoryControl(SAMPLE_CONSOLE_VIEW,'owner','owner:claim:4')?.actions).not.toContain('spot.confirm');expect(memoryControl(SAMPLE_CONSOLE_VIEW,'owner','owner:claim:7')?.actions).toEqual(['spot.forget']);expect(resolveMemoryAction(SAMPLE_CONSOLE_VIEW,'owner',{action:'spot.dismiss',id:'owner:claim:7',value:''})).toBeNull();});
 it('does not expose withheld text or source pointers from retry control reads',()=>{const read=JSON.stringify(memoryControl(SAMPLE_CONSOLE_VIEW,'owner','owner:claim:7'));expect(read).not.toContain('phone');expect(read).not.toContain('evidence');expect(read).not.toContain('source_ref');expect(read).toContain('purging');});
 it('keeps pattern forget separate from its supporting Spot actions',()=>{expect(memoryControl(SAMPLE_CONSOLE_VIEW,'owner','owner:node:1')?.actions).toEqual(['node.forget']);expect(resolveMemoryAction(SAMPLE_CONSOLE_VIEW,'owner',{action:'spot.forget',id:'owner:node:1',value:''})).toBeNull();});
 it('changes the action revision when same-ID reviewed content changes',async()=>{const before=projectMemoryControl(SAMPLE_CONSOLE_VIEW,'owner','owner:claim:5');const changed={...SAMPLE_CONSOLE_VIEW,spots:SAMPLE_CONSOLE_VIEW.spots.map(c=>c.id===5?{...c,text:'Corrected saved preference'}:c)};expect(await controlRevision(projectMemoryControl(changed,'owner','owner:claim:5'))).not.toBe(await controlRevision(before));});
});
