import {readFileSync} from 'node:fs';
import {expect,it} from 'vitest';
import {parseNativeCaseBundle} from '../evals/native-case-bundle';
import {inspectNativeManifest} from '../evals/native-manifest';
import {inspectNativeExecutionSupport} from '../evals/native-execution-readiness';
import {loadNativeSuite} from '../evals/waldo-native-suite';
import {IsolatedSourceWorld} from '../scenarios/isolated-source-world';
import {nativeSelectedSource} from '../scenarios/native-selected-source';
import {isolatedGoogleClient} from '../scenarios/isolated-google-client';
const path=new URL('../evals/fixtures/native36-core/v1/W03.json',import.meta.url);
it('W03 is contract-conformant with byte-exact pins and no external effect',()=>{
 const {bundle:b}=parseNativeCaseBundle(readFileSync(path,'utf8'));
 expect(inspectNativeManifest(b.manifest).status).toBe('ready_for_isolated_trial');
 expect(inspectNativeExecutionSupport(b,{source_families:['calendar','mail','tasks'],effect_kinds:[],turn_kinds:['owner_text','provider_event'],production_tools:['query_calendar','get_communication','read_thread','get_tasks']})).toEqual([]);
 const spec=loadNativeSuite().find(s=>s.id==='W03')!;
 expect((b.decisions[0]!.synthetic_value as {pinned_facts:string[]}).pinned_facts).toEqual(spec.fixture.facts);
 expect(b.manifest.visible_prompt).toBe(spec.user_prompt);
 expect(b.manifest.world.clock).toBe(spec.fixture.now);
 expect(b.required_effect_kinds).toEqual([]);
});
it('backlog is 12h, free time is 4h, family commitment is fixed; control data stays unreadable',async()=>{
 const {bundle:b}=parseNativeCaseBundle(readFileSync(path,'utf8'));const w=new IsolatedSourceWorld(b.manifest.world);
 const o=b.manifest.candidate_owner;
 const api=isolatedGoogleClient(nativeSelectedSource(w,o,b.selected_source_ids),o);
 const tasks=await api.tasks('todo',50);
 const hours=tasks.reduce((n,t)=>n+Number(/ - ([0-9.]+)h$/.exec(t.title)![1]),0);
 expect(tasks).toHaveLength(7);expect(hours).toBe(12);
 const day=await api.events('2026-10-05T09:00:00+05:30','2026-10-05T17:00:00+05:30',20,false);
 const busy=day.reduce((n,e)=>n+(Date.parse(e.end)-Date.parse(e.start))/3600000,0);
 expect(8-busy).toBe(4);
 const night=await api.events('2026-10-05T18:00:00+05:30','2026-10-05T22:00:00+05:30',20,false);
 expect(night.map(e=>e.title)).toEqual(['Family dinner (fixed)']);
 const thread=await api.readThread('northwind',20);
 expect(thread).toHaveLength(2);expect(JSON.stringify([tasks,day,thread])).not.toContain('CONTROL_');
 const restricted=nativeSelectedSource(w,o,b.selected_source_ids);
 expect(()=>restricted.read(o,'mail','control-mail')).toThrow();
 expect(()=>restricted.read(b.manifest.control_owner,'tasks','t-northwind')).toThrow();
 expect(w.accessLog(b.manifest.control_owner)).toEqual([]);
 expect(w.outbox(o)).toEqual([]);expect(w.outbox(b.manifest.control_owner)).toEqual([]);
});
