import {expect,it} from 'vitest';
import {ownerContextHandler} from '../src/tools/live/owner-context';
const row={id:1,kind:'preference',text:'Usually gym11am; evening when mornings fail',source:'owner-chat',evidence:'original words',origin:'owner',status:'active',created_at:'2026-09-30T01:00:00Z',last_seen_at:'2026-09-30T01:00:00Z',seen_count:1,source_ref:'owner-message-1',verification_status:'owner-grounded'};
it('actual handler returns conditional whole statements and provenance without action permission',async()=>{const seen:unknown[]=[];const h=ownerContextHandler({recall:(q,l)=>{seen.push([q,l]);return [row];}});expect(await h.handle({topic:'gym',limit:8},{} as never)).toMatchObject({ok:true,source_taint:'external',data:{authority:'context_only_not_action_approval',claims:[{text:row.text,evidence:row.evidence,source_ref:row.source_ref,verification_status:'owner-grounded'}]}});expect(seen).toEqual([['gym',8]]);});
it('retired,forgotten,untrusted and temporally ended rows excluded even if supplier returns them',async()=>{const h=ownerContextHandler({recall:()=>[{...row,status:'forgotten'},{...row,status:'superseded'},{...row,origin:'untrusted'},{...row,valid_to:'2026-09-30T02:00:00Z'},row]});expect(await h.handle({topic:'gym',limit:8},{} as never)).toMatchObject({data:{claims:[{id:1}]}});});
it('missing owner-local store is honest unavailable; schema denies ownerID/context override',async()=>{const h=ownerContextHandler(undefined);expect(await h.handle({topic:'gym',limit:8},{} as never)).toMatchObject({ok:false,source_taint:'external'});expect(h.schema.safeParse({topic:'gym',owner_id:'other'}).success).toBe(false);});
// Exercise the real owner-local store, not just a permissive retrieval stub.
it('real separate DO memory stores cannot cross owner, forget removes hits',async()=>{
 const {env}=await import('cloudflare:workers');const {runInDurableObject}=await import('cloudflare:test');const {claimStore}=await import('../src/memory/claims');
 const a=env.TELEGRAM_OWNER_DO!.get(env.TELEGRAM_OWNER_DO!.idFromName('context-read-a')),b=env.TELEGRAM_OWNER_DO!.get(env.TELEGRAM_OWNER_DO!.idFromName('context-read-b'));
 const result=await runInDurableObject(a,async(_i,state)=>{const s=claimStore(state.storage.sql);s.add({kind:'preference',text:'Cedar gym original',source:'owner-chat',evidence:'Cedar original',origin:'owner',source_ref:'owner-1'},'2026-09-30T01:00:00Z',77);const h=ownerContextHandler(s);const before=await h.handle({topic:'Cedar',limit:8},{} as never);s.forget(77);const after=await h.handle({topic:'Cedar',limit:8},{} as never);return{before,after};});
 expect(result.before).toMatchObject({data:{claims:[{text:'Cedar gym original'}]}});expect(result.after).toMatchObject({data:{claims:[]}});
 const other=await runInDurableObject(b,async(_i,state)=>ownerContextHandler(claimStore(state.storage.sql)).handle({topic:'Cedar',limit:8},{} as never));expect(other).toMatchObject({data:{claims:[]}});
});

it('real transactional correction returns only replacement with supersession evidence',async()=>{
 const {env}=await import('cloudflare:workers');const {runInDurableObject}=await import('cloudflare:test');const {claimStore}=await import('../src/memory/claims');const stub=env.TELEGRAM_OWNER_DO!.get(env.TELEGRAM_OWNER_DO!.idFromName('context-correct'));
 const result=await runInDurableObject(stub,async(_i,state)=>{const s=claimStore(state.storage.sql,work=>state.storage.transactionSync(work));s.add({kind:'preference',text:'Birch gym mornings',source:'owner-chat',evidence:'old',origin:'owner',source_ref:'original'},'2026-09-30T01:00:00Z',77);expect(s.correct(77,{kind:'preference',text:'Birch gym evenings unless meeting',source:'owner-chat',evidence:'new conditional original',origin:'owner',source_ref:'correction'},'2026-09-30T02:00:00Z')).toBe(true);return ownerContextHandler(s).handle({topic:'Birch',limit:8},{} as never);});
 expect(result).toMatchObject({data:{claims:[{text:'Birch gym evenings unless meeting',supersedes_id:77,source_ref:'correction'}]}});expect((result as {data:{claims:unknown[]}}).data.claims).toHaveLength(1);
});
it('oversized whole claim is explicitly omitted, never cut into misleading partial words',async()=>{const h=ownerContextHandler({recall:()=>[{...row,text:'gym '.repeat(20000)}, {...row,id:2}]});const result=await h.handle({topic:'gym',limit:8},{} as never);expect(result).toMatchObject({data:{claims:[{id:2,text:row.text}],omitted_claim_ids:[1],complete:false}});});
it('actual dispatcher schema gate admits context read while preserving external taint',async()=>{const {dispatchTool}=await import('../src/tools/dispatcher');const {buildSessionState}=await import('@waldo/contracts');const {sanitise}=await import('../src/scribe/sanitiser');const context={authenticatedUserId:'owner',trigger:'user_message' as const,session:buildSessionState({trigger:'user_message',canary_tokens:['1111111111111111','2222222222222222','3333333333333333'],started_at:1}),hasApproval:()=>false,sourceTaint:null,toolArgSourceTaint:null,sanitise};expect(await dispatchTool({id:'owner-context-read',name:'read_owner_context',args:{topic:'gym'}},context,{handlers:[ownerContextHandler({recall:()=>[row]})]})).toMatchObject({ok:true,source_taint:'external',data:{authority:'context_only_not_action_approval',claims:[{id:1}]}});});
