import {expect,it,vi} from 'vitest';
import {WALDO_CHAT_MODEL} from '@waldo/contracts';
import {ownerBrowserRuntime} from '../src/channels/owner-browser-runtime';
import {registerCommonBrowserSdk} from '../src/channels/common-staging-registration';
import {commonBrowserFixtureLoader} from './fixtures/common-browser-sdk';
import type {RunEffectScope} from '../src/channels/run-effect-scope';
const fake=vi.hoisted(()=>({calls:0,single:[] as boolean[],custody:'a'.repeat(64),wait:undefined as undefined|(()=>Promise<void>)}));
vi.mock('../src/llm/openai',()=>({OpenAIResponsesAdapter:class{constructor(options:{singleAttempt?:boolean}){fake.single.push(!!options.singleAttempt);}async complete(_request:unknown){fake.calls++;return {ok:true,data:{text:'public result'}};}}}));
vi.mock('../src/identity/common-owner-authority',()=>({commonOwnerAuthority:()=>({resolve:async(_p:string,subject:string,doName:string)=>{await fake.wait?.();return {directoryOwnerId:'10000000-0000-0000-0000-000000000001',custodyDigest:fake.custody,subject,doName};}})}));
it('ordinary automatic owner host meters its first request, denies third run and ninth call before I/O, and keeps the gate after reconstruction/removal',async()=>{
 registerCommonBrowserSdk(commonBrowserFixtureLoader);
 const now=Date.now(),rows=new Map<string,any>([['do_name','test-owner'],['telegram_subject','1']]);
 const storage={kv:{get:(k:string)=>structuredClone(rows.get(k)),put:(k:string,v:any)=>rows.set(k,structuredClone(v)),list:({prefix}:{prefix:string})=>[...rows].filter(([k])=>k.startsWith(prefix))},transactionSync:(work:()=>unknown)=>work()} as unknown as DurableObjectStorage;
 const raw={scope:'verified_owners',policy:{ref:'existing-approval',createdAt:now-1000,expiresAt:now+60000,allowedOrigins:['*'],maxAllocations:1,maxReservedBrowserMs:120000,lifetimeMs:60000,maxScreenshotBytes:1024},billing:{cloudflareAccountId:'a'.repeat(32),conservativeWorstCase:true},spend:{limitMicrousd:20000000,maxCalls:30,validUntil:now+60000},acceptance:{doName:'test-owner',subject:'1',directoryOwnerId:'10000000-0000-0000-0000-000000000001',expiresAt:now+60000,maxRuns:2,maxModelCalls:8,priorRuns:0,priorModelCalls:0,priorMicrousd:0}};
 const env={WALDO_ENVIRONMENT:'staging',COMMON_BROWSER_REGISTRATION:JSON.stringify(raw),BROWSER:{fetch:vi.fn()},TELEGRAM_OWNER_DO:{idFromName:(name:string)=>({toString:()=>name==='test-owner'?'physical':'other'})}} as never;
 const scope=(runId:string):RunEffectScope=>({runId,attempt:'canonical',deadline:now+60000,signal:new AbortController().signal,admit(){},commit:work=>work()});
 let active=scope('first');const make=()=>ownerBrowserRuntime({env,storage,actualDoId:'physical',activeScope:()=>active});
 const gateway=make().gateway()!;const call=()=>gateway.complete({request:{model:WALDO_CHAT_MODEL,max_tokens:32},runScope:active} as never);
 await call();expect(fake.calls).toBe(1);expect(fake.single).toEqual([true]);
 const key='common-spend:existing-approval:owner:10000000-0000-0000-0000-000000000001';
 expect(rows.get(key).calls).toHaveLength(1);expect(rows.get(key).reservedMicrousd).toBeGreaterThan(0);
 await expect(make().gateway()!.complete({request:{model:WALDO_CHAT_MODEL,max_tokens:32},runScope:active} as never)).rejects.toThrow(/reconciliation/);
 active=scope('second');await call();active=scope('third');await expect(call()).rejects.toThrow(/run limit/);
 active=scope('first');for(let n=0;n<6;n++)await call();await expect(call()).rejects.toThrow(/model limit/);expect(fake.calls).toBe(8);
 (env as any).COMMON_BROWSER_REGISTRATION='';active=scope('after-removal');await expect(make().gateway()!.complete({request:{model:WALDO_CHAT_MODEL,max_tokens:32},runScope:active} as never)).rejects.toThrow();expect(fake.calls).toBe(8);
});


it('manual acceptance capsule or whole registration removal cannot resume unmetered owner calls',async()=>{
 const now=Date.now(),rows=new Map<string,any>([['do_name','test-owner'],['telegram_subject','1']]);
 const storage={kv:{get:(k:string)=>structuredClone(rows.get(k)),put:(k:string,v:any)=>rows.set(k,structuredClone(v)),list:({prefix}:{prefix:string})=>[...rows].filter(([k])=>k.startsWith(prefix))},transactionSync:(work:()=>unknown)=>work()} as unknown as DurableObjectStorage;
 const identity={doName:'test-owner',subject:'1',directoryOwnerId:'10000000-0000-0000-0000-000000000001'};
 const raw:any={policy:{...identity,ref:'manual-approval',createdAt:now-1000,expiresAt:now+60000,allowedOrigins:['*'],maxAllocations:1,maxReservedBrowserMs:120000,lifetimeMs:60000,maxScreenshotBytes:1024},billing:{cloudflareAccountId:'a'.repeat(32),conservativeWorstCase:true},spend:{limitMicrousd:20000000,maxCalls:30,validUntil:now+60000},acceptance:{...identity,expiresAt:now+60000,maxRuns:2,maxModelCalls:8,priorRuns:0,priorModelCalls:0,priorMicrousd:0}};
 const env={WALDO_ENVIRONMENT:'staging',COMMON_BROWSER_REGISTRATION:JSON.stringify(raw),BROWSER:{},TELEGRAM_OWNER_DO:{idFromName:()=>({toString:()=> 'physical'})}} as never;
 const scope:RunEffectScope={runId:'manual-first',attempt:'canonical',deadline:now+60000,signal:new AbortController().signal,admit(){},commit:work=>work()};
 let current=scope;const make=()=>ownerBrowserRuntime({env,storage,actualDoId:'physical',activeScope:()=>current}).gateway()!;
 const initial=fake.calls;delete (env as any).BROWSER;
 await expect(make().complete({request:{model:WALDO_CHAT_MODEL,max_tokens:32},runScope:scope} as never)).rejects.toThrow();expect(fake.calls).toBe(initial);expect(rows.size).toBe(2);
 (env as any).BROWSER={};
 await make().complete({request:{model:WALDO_CHAT_MODEL,max_tokens:32},runScope:scope} as never);const issued=fake.calls;
 let entered!:()=>void,release!:()=>void;const ready=new Promise<void>(resolve=>entered=resolve),wait=new Promise<void>(resolve=>release=resolve);
 fake.wait=async()=>{entered();await wait;};
 const pending=make().complete({request:{model:WALDO_CHAT_MODEL,max_tokens:32},runScope:scope} as never);await ready;
 current={...scope,runId:'new-active'};release();await expect(pending).rejects.toThrow();fake.wait=undefined;current=scope;expect(fake.calls).toBe(issued);
 fake.custody='b'.repeat(64);await expect(make().complete({request:{model:WALDO_CHAT_MODEL,max_tokens:32},runScope:scope} as never)).rejects.toThrow(/custody changed/);fake.custody='a'.repeat(64);expect(fake.calls).toBe(issued);
 delete raw.acceptance;(env as any).COMMON_BROWSER_REGISTRATION=JSON.stringify(raw);
 await expect(make().complete({request:{model:WALDO_CHAT_MODEL,max_tokens:32},runScope:scope} as never)).rejects.toThrow(/policy missing/);
 raw.policy.ref='rotated-ref';(env as any).COMMON_BROWSER_REGISTRATION=JSON.stringify(raw);
 expect(()=>make()).toThrow(/ref requires reconciliation/);expect(fake.calls).toBe(issued);
 (env as any).COMMON_BROWSER_REGISTRATION='';
 await expect(make().complete({request:{model:WALDO_CHAT_MODEL,max_tokens:32},runScope:scope} as never)).rejects.toThrow();expect(fake.calls).toBe(issued);
});
