import {describe,expect,it,vi} from 'vitest';
import {ownerSchedulerAdmission,type OwnerSchedulerBinding} from '../src/identity/owner-scheduler-admission';
import {createOwnerTurnContext} from '../src/context-composer/owner-turn';
import type {RunEffectScope} from '../src/channels/run-effect-scope';
const at=Date.parse('2026-10-10T10:00:00Z');
const row=():OwnerSchedulerBinding=>({ownerId:'10000000-0000-0000-0000-000000000001',ownerDoName:'canonical-app-only-owner',physicalDoId:'physical-owner-do',ownerRevision:'9007199254740993',sourceRevision:'grant-3-policy-2',scheduleRef:'owner-proactivity',scheduleRevision:'occurrence-1',enabled:true});
const fixture=()=>{let current=row(),now=at,closed=false;const scope:RunEffectScope={runId:'background-source-check',attempt:'attempt-1',deadline:at+60000,signal:new AbortController().signal,admit:()=>{if(closed)throw new Error('run closed');},commit:work=>work()};const lookup=vi.fn(async()=>current);const options={scope,lookup,expectedOwnerDoName:current.ownerDoName,expectedPhysicalDoId:current.physicalDoId,occurrenceKey:'alarm:1',occurredAt:at,intent:'run_patrol' as const,purpose:'source_discovery' as const,now:()=>now};return {options,change:(patch:Partial<OwnerSchedulerBinding>)=>{current={...current,...patch};},close:()=>{closed=true;},advance:()=>{now=at+60001;}};};
describe('canonical owner scheduler admission',()=>{
  it('admits app-only owner patrol as trusted scheduler metadata rather than an owner message',async()=>{const f=fixture(),admitted=await ownerSchedulerAdmission(f.options),input=await admitted.readInput();expect(admitted.invocation.admission_source).toBe('trusted_scheduler');expect(admitted.invocation.runtime_binding.trigger).toBe('patrol');expect(input.source.source_kind).toBe('runtime_metadata');expect(input.source.scope).toBe('invocation');expect(input.text).not.toContain('telegram');expect(Object.isFrozen(admitted.invocation)).toBe(true);
    const context=createOwnerTurnContext(admitted,{now:()=>at});const snap=context.snapshot();const result=await context.composer.compose(admitted.invocation,{...snap,canary_tokens:['1111111111111111','2222222222222222','3333333333333333'],replay_context_ref:null});expect(result.ok).toBe(true);
  });
  it('fences owner/physical/source/schedule/enablement changes at every input read',async()=>{for(const patch of [{ownerId:'10000000-0000-0000-0000-000000000002'},{physicalDoId:'foreign-do'},{ownerDoName:'other-owner'},{ownerRevision:'9007199254740994'},{sourceRevision:'revoked-grant'},{scheduleRevision:'corrected'},{enabled:false}]){const f=fixture(),admitted=await ownerSchedulerAdmission(f.options);f.change(patch);await expect(admitted.readInput()).rejects.toMatchObject({code:'rejected'});}});
  it('requires bounded live scope and rejects closed/expired execution',async()=>{const f=fixture(),admitted=await ownerSchedulerAdmission(f.options);f.close();await expect(admitted.assertCurrent()).rejects.toThrow('run closed');const g=fixture(),other=await ownerSchedulerAdmission(g.options);g.advance();await expect(other.readInput()).rejects.toMatchObject({code:'rejected'});const h=fixture();await expect(ownerSchedulerAdmission({...h.options,scope:{...h.options.scope,deadline:at+16*60000}})).rejects.toMatchObject({code:'rejected'});});
  it('does not execute hostile receipt accessors or admit malformed authority',async()=>{const f=fixture(),getter=vi.fn(()=>row().ownerId),hostile={...row()};Object.defineProperty(hostile,'ownerId',{get:getter,enumerable:true});await expect(ownerSchedulerAdmission({...f.options,lookup:async()=>hostile})).rejects.toMatchObject({code:'rejected'});expect(getter).not.toHaveBeenCalled();});
  it('retry occurrence identity remains stable while its admitted source revision changes authority digest',async()=>{const f=fixture(),a=await ownerSchedulerAdmission(f.options),b=await ownerSchedulerAdmission(f.options);expect(a.invocation.idempotency.key_ref).toBe(b.invocation.idempotency.key_ref);f.change({sourceRevision:'grant-4'});const c=await ownerSchedulerAdmission(f.options);expect(c.invocation.verified_authority.verification_ref).not.toBe(a.invocation.verified_authority.verification_ref);expect(c.invocation.input_refs[0]!.content_digest).not.toBe(a.invocation.input_refs[0]!.content_digest);});
});
