FROM docker.io/library/node:24-trixie-slim@sha256:173f125896c3b47ddf056734c7ea789d04595a6a08769a8f78e0df642781fb66
RUN mkdir /workspace && chown node:node /workspace
USER node
WORKDIR /workspace
CMD ["sleep", "35"]
