// Hermetic scripted validation of new supervisor, never actual model/native run.
import {readFileSync} from 'node:fs';
import {parseNativeCaseBundle} from './evals/native-case-bundle';
import { createHash } from 'node:crypto';
import { cloudflareTest } from '@cloudflare/vitest-pool-workers';
import { defineConfig } from 'vitest/config';
import { loadNativeSuite,WALDO_NATIVE_SUITE_SHA256 } from './evals/waldo-native-suite';
import {OPENAI_GPT_6_LUNA_MODEL as WALDO_CHAT_MODEL} from '../contracts/src/model/roster';
import { NATIVE_BASELINE_HEAD } from './evals/native-runner';
const spec=loadNativeSuite().find(s=>s.id==='W23')!;
const sources={calendar:[{owner_id:'a@example.invalid',id:'c',title:'Unit admin',start:'2026-10-01T09:00:00+05:30',end:'2026-10-01T09:30:00+05:30'}],priorities:[{owner_id:'a@example.invalid',id:'p',text:'Unit board prep'}]};
const bundle={version:1,suite_digest:WALDO_NATIVE_SUITE_SHA256,baseline_head:NATIVE_BASELINE_HEAD,revision:'unit-scripted-incomplete',manifest:{case_id:'W23',candidate_owner:'a@example.invalid',control_owner:'b@example.invalid',visible_prompt:spec.user_prompt,world:{clock:spec.fixture.now,owners:[{id:'a@example.invalid'},{id:'b@example.invalid'}],sources,revisions:[{at:new Date(Date.parse(spec.fixture.now)+60000).toISOString(),owner_id:'a@example.invalid',source:'calendar',id:'c',patch:{title:'Revised unit admin'}}]},grants:[{owner_id:'a@example.invalid',purpose:'unitread',scope:'selected',allowed_effects:[],effective_at:'2026-10-01T00:00:00+05:30',expires_at:'2026-11-01T00:00:00+05:30'}],branches:[],supported_tools:['query_calendar'],source_digest:`sha256:${createHash('sha256').update(JSON.stringify(sources)).digest('hex')}`},selected_source_ids:{calendar:['c'],priorities:['p']},decisions:[],turns:[{id:'initial',kind:'owner_text',at:spec.fixture.now,text:spec.user_prompt},{id:'revision',kind:'provider_event',at:new Date(Date.parse(spec.fixture.now)+60000).toISOString(),payload:{owner_id:'a@example.invalid',source:'calendar',id:'c',patch:{title:'Revised unit admin'}}},{id:'followup',kind:'owner_text',at:new Date(Date.parse(spec.fixture.now)+120000).toISOString(),text:'Thanks. What is next on my calendar?'}],required_source_families:['calendar','priorities'],required_effect_kinds:[],readiness:{sources_complete:false,branches_complete:false,provider_readback_complete:false,missing:['unit diagnostic only']}};
const diagnosticInput=process.env.WALDO_NATIVE_DIAGNOSTIC_BUNDLE?parseNativeCaseBundle(readFileSync(process.env.WALDO_NATIVE_DIAGNOSTIC_BUNDLE,'utf8')):{bundle,digest:'unit-scripted-no-native-digest'};
export default defineConfig({test:{include:['test/owner-do-native-trial.ts'],testTimeout:30000},plugins:[cloudflareTest({miniflare:{bindings:{WALDO_ENV:'test',RUN_LOOP_PROVIDER_MODE:'fake',RUN_LOOP_LOCAL_INGRESS_TOKEN:'test-run-loop-local-token-000000000000',RESPONSIBILITY_INGRESS_HMAC_SECRET:'test-responsibility-ingress-hmac-secret-000000000000',TELEGRAM_BOT_TOKEN:'fictional-native-bot',TELEGRAM_WEBHOOK_SECRET:'fictional-native-secret',OPENAI_API_KEY:'sk-test-native-scripted-000000000000000000000000000000',GOOGLE_CLIENT_ID:'fictional-native-google',GOOGLE_CLIENT_SECRET:'fictional-native-google',WALDO_NATIVE_MAX_OUTPUT_TOKENS:'4096',WALDO_NATIVE_SCRIPTED:'diagnostic_only',WALDO_NATIVE_MODEL:WALDO_CHAT_MODEL,WALDO_NATIVE_BUNDLES:JSON.stringify([diagnosticInput])}},wrangler:{configPath:'./wrangler.jsonc'}})]});
