import { expect, it, vi } from 'vitest';
import { iMessageResultSchema } from '@waldo/contracts';
import { syntheticIMessageEvents } from '../../contracts/src/channels/imessage-v1-fixtures';
import { fixture, relayPolicy, digest, pause } from './connector-fixtures';
import { HostMailboxTransport } from '../src/connector/mailbox-transport';
import { signAndExecute } from '../src/connector/outbound';
const setup = () => { const f = fixture(); const transport = new HostMailboxTransport(f.mailbox, f.relayStore, f.account.binding.bridgeId, f.account.binding.accountId, { deliveryDeadlineMs: 20, relayMutationDeadlineMs: relayPolicy.mutationDeadlineMs, source: 'synthetic test policy' }); return { ...f, transport, send: (id = 'synthetic-command') => signAndExecute(f.relay, transport, f.account, f.command(id), () => f.clock.now, 'synthetic-send-' + id) }; };
async function host(f: ReturnType<typeof setup>, resultChange: Record<string, unknown> = {}) {
    const r = f.pullRequest(), pulled = await f.mailbox.pull(r.body, r.headers, { waitMs: 100 });
    expect(pulled.delivery).not.toBeNull();
    const d = pulled.delivery!;
    const c = JSON.parse(d.body);
    const result = { version: 1, commandId: c.commandId, target: c.target, state: 'local_recorded', messageGuid: 'synthetic-sent-guid', evidence: { kind: 'local_database', reference: 'synthetic-row' }, ...resultChange };
    const post = f.signed({ version: 1, bridgeId: c.binding.bridgeId, accountId: c.binding.accountId, deliveryId: d.deliveryId, commandId: c.commandId, commandDigest: digest(d.body), result });
    return { post, result, d };
}
it('T2 missing/stale/unverified capabilities never enqueue; flags remain unchanged', async () => { const f = setup(); f.heartbeat(); expect((await f.transport.probe()).readiness).toBe('offline'); expect((await f.send()).state).toBe('rejected'); expect(f.mailboxStore.snapshot().deliveries).toHaveLength(0); f.report({ ...f.caps(), readiness: 'unverified' }); expect((await f.send('synthetic-unverified')).state).toBe('rejected'); const noSend = f.caps(); noSend.features.text.send = false; f.report(noSend);
    expect(await f.send('synthetic-no-send')).toMatchObject({reason:'capability_unverified'});
    const other = new HostMailboxTransport(f.mailbox,f.relayStore,'synthetic-other-bridge','synthetic-other-account',f.transport.policy);
    expect(await other.probe()).toMatchObject({readiness:'offline',bridgeId:'synthetic-other-bridge',accountId:'synthetic-other-account'});
    f.clock.now += 501; expect((await f.transport.probe()).readiness).toBe('offline'); });
it('T1 signed relay send, host pull/result, local record and correlation', async () => { const f = setup(); f.report(); f.heartbeat(); const sent = f.send(); const h = await host(f); f.mailbox.postResult(h.post.body, h.post.headers); expect(await sent).toEqual(h.result); expect(f.relayStore.snapshot().commands[0]!.state).toBe('settled'); expect(f.mailboxStore.snapshot().sentMessages[0]!.commandId).toBe('synthetic-command'); });
it('T3 no pull withdraws safely and permits a new stable command id', async () => { const f = setup(); f.report(); f.heartbeat(); expect(await f.send()).toMatchObject({ state: 'rejected', reason: 'host_not_pulled' }); expect(f.mailboxStore.snapshot().deliveries[0]!.state).toBe('withdrawn'); expect(await f.send('synthetic-next')).toMatchObject({ reason: 'host_not_pulled' }); });
it('T4 pulled/no result quarantines, late evidence cannot clear it', async () => { const f = setup(); f.report(); f.heartbeat(); const sent = f.send(); const h = await host(f); expect(await sent).toMatchObject({ state: 'unknown', disposition: 'still_in_flight' }); f.mailbox.postResult(h.post.body, h.post.headers); expect(f.relayStore.snapshot().commands[0]!.state).toBe('quarantined'); expect(await f.send('synthetic-next')).toMatchObject({ reason: 'mutation_lane_poisoned' }); expect(f.mailboxStore.snapshot().deliveries).toHaveLength(1); });
it.each(['commandId', 'target'])('T5 invalid %s result is rejected and relay quarantines on its deadline', async (field) => { const f = setup(); f.report(); f.heartbeat(); const sent = f.send(); const h = await host(f, field === 'commandId' ? { commandId: 'synthetic-wrong' } : { target: { ...f.command().target, chatGuid: 'synthetic-wrong' } }); expect(() => f.mailbox.postResult(h.post.body, h.post.headers)).toThrow('mismatch'); expect(await sent).toMatchObject({ state: 'unknown', reason: 'transport_result_unavailable' }); });
it('T6 concurrent duplicate and settled repeat produce exactly one delivery', async () => { const f = setup(); f.report(); f.heartbeat(); const sent = f.send(); const h = await host(f); expect(await f.send()).toMatchObject({ reason: 'concurrent_in_flight' }); f.mailbox.postResult(h.post.body, h.post.headers); await sent; expect(await f.send()).toEqual(h.result); expect(f.mailboxStore.snapshot().deliveries).toHaveLength(1); });
it('T7 offline heartbeat refuses before enqueue', async () => { const f = setup(); f.report(); expect(await f.send()).toMatchObject({ reason: 'relay_offline' }); expect(f.mailboxStore.snapshot().deliveries).toHaveLength(0); });
it('T8 binding changes during awaited probe are fenced by the relay', async () => { const f = setup(); f.report(); f.heartbeat(); const original = f.transport.forSignedCommand.bind(f.transport); vi.spyOn(f.transport, 'forSignedCommand').mockImplementation((body, headers) => { const scoped = original(body, headers); const probe = scoped.probe.bind(scoped); scoped.probe = async () => { const caps = await probe(); f.account.binding = { ...f.account.binding, chatGuid: 'synthetic-replacement' }; return caps; }; return scoped; }); expect(await f.send()).toMatchObject({ reason: 'relay_binding_changed' }); expect(f.mailboxStore.snapshot().deliveries).toHaveLength(0); });
it('T9 history uses pending bodies and opaque cursor insertion order only', async () => { const f = setup(); for (const [i, value] of ['z', 'a'].entries()) {
    const r = f.signed({ ...syntheticIMessageEvents.text, eventId: 'synthetic-event-' + i, cursor: { databaseGeneration: 'fixture-generation', value } });
    f.relay.admit(r.body, r.headers);
} expect((await f.transport.history('fixture-generation', 'z')).events.map(e => e.cursor.value)).toEqual(['a']); await expect(f.transport.history('synthetic-wrong', null)).rejects.toThrow('generation'); await expect(f.transport.history('fixture-generation', 'synthetic-wrong')).rejects.toThrow('cursor'); await f.relay.flush(async (body) => ({ admitted: true, eventId: JSON.parse(body).eventId, digest: digest(body) })); expect((await f.transport.history('fixture-generation', null)).events).toEqual([]); });
it('delivery evidence is retained but never returned as a delivered send claim', async () => { const f = setup(); f.report(); f.heartbeat(); const sent = f.send(); const h = await host(f, { state: 'delivered', evidence: { kind: 'transport_delivery', reference: 'synthetic-evidence' } }); f.mailbox.postResult(h.post.body, h.post.headers); expect(await sent).toMatchObject({ state: 'unknown' }); expect(f.mailboxStore.snapshot().sentMessages[0]!.state).toBe('delivered'); });
it('requires sourced deadlines and a scoped signed envelope', async () => { const f = setup(); expect(() => new HostMailboxTransport(f.mailbox, f.relayStore, 'synthetic-bridge', 'synthetic-account', { deliveryDeadlineMs: 80, relayMutationDeadlineMs: 80, source: 'synthetic-policy' })).toThrow(); await expect(f.transport.execute(f.command())).rejects.toThrow('signed_command_required'); });
