// Synthetic Memory contract data for rendered verification only. Never bundled.
export function memoryPreview(params, partial=false) {
 const header={version:1,state:partial?'partial':'available',complete:!partial,unavailable_claim_count:partial?1:0,actions:[]};
 const claims=Array.from({length:28},(_,i)=>({id:`synthetic-owner:claim:${i+1}`,local_id:i+1,kind:'preference',text:i===0?'Keep mornings gentle':`Synthetic Spot ${i+1}`,source:'inferred',origin:i===0?'shared':'owner',status:'active',evidence:{kind:'writer_note',text:'A synthetic writer note, not proof of truth.'},source_reference:{state:'unverified',link:null},recorded_at:'2026-10-01T00:00:00Z',writer_seen_count:1}));
 const nodes=Array.from({length:16},(_,i)=>({id:`synthetic-owner:node:${i+1}`,type:'interpretation',local_id:i+1,label:['Gentler mornings','Focus and recovery','Room to breathe'][i]??`Saved pattern ${i+1}`,summary:'A tentative interpretation from saved support.',domain:'day',stored_status:i===2?'stale':'active',recorded_active_at:'2026-10-01T00:00:00Z',estimate:.4,estimate_kind:'uncalibrated_model_estimate',support:{claim_ids:[claims[i].id],unavailable_count:0,independent_observations:'unverified'}}));
 const view=params.get('view'),id=params.get('id');
 if(view==='claims'||view==='interpretations') {const rows=view==='claims'?claims:nodes,start=params.get('cursor')?25:0,items=rows.slice(start,start+25);return {...header,view,items,page:{limit:25,returned:items.length,total:rows.length,next_cursor:rows.length>start+25?'synthetic-page-2':null}};}
 if(view==='detail') {const item=claims.find(c=>c.id===id)??nodes.find(n=>n.id===id);if(!item)return {error:'not_found'};return 'text' in item?{...header,view,kind:'claim',item,linked_interpretation_ids:[nodes[0].id]}:{...header,view,kind:'interpretation',item,support_claim_ids:item.support.claim_ids,support_unavailable_count:0};}
 const center=nodes.find(n=>n.id===id);if(!center)return {error:'not_found'};const neighbors=nodes.filter(n=>n.id!==id),start=params.get('cursor')?12:0,shown=neighbors.slice(start,start+12),links=shown.map(n=>({from:id,to:n.id,relation:'possible support',state:'unverified_association',estimate:.3}));
 return {...header,view:'pattern',center,nodes:shown,associations:links,showing:{nodes:shown.length,of_nodes:neighbors.length,links:links.length,of_links:neighbors.length},truncated:neighbors.length>start+12,omitted_links:Math.max(0,neighbors.length-start-12),expand:{next_cursor:neighbors.length>start+12?'synthetic-pattern-2':null,links_capped:false,capped_links_recoverable:false,capped_links:0}};
}
