// Synthetic Memory contract data for rendered verification only. Never bundled.
export function memoryPreview(params, partial=false) {
 const header={version:1,state:partial?'partial':'available',complete:!partial,unavailable_claim_count:partial?1:0,actions:[]};
 const texts=['Keep mornings gentle','Deep work before noon','Calls after lunch','Runs on Tuesdays and Saturdays','Coffee after 3pm hurts sleep','Prefers short replies','Board prep needs a quiet hour','Walks between meetings','Dinner with family on Sundays','Reads before bed','Avoids meetings on Friday afternoons','Likes plans written down','Late nights before launches','Checks Slack first thing','Lunch at the desk on busy days','Flights: aisle seat','Answers email in batches','Gym after work on Mondays','Takes calls while walking','Prefers WhatsApp for family','Plans the week on Sunday night','Forgets to drink water','Book club on the last Thursday','Wakes around 6:30','Naps after long flights','Likes a short morning list','Turns off notifications at 10pm','Prefers video off for 1:1s'];
 const sources=['inferred','stated','inferred','confirmed','inferred','stated','inferred'];
 const claims=texts.map((text,i)=>({id:`synthetic-owner:claim:${i+1}`,local_id:i+1,kind:'preference',text,source:sources[i%sources.length],origin:i===0?'shared':'owner',status:'active',evidence:{kind:'writer_note',text:'Noticed across several days in chat and calendar. A synthetic note, not proof of truth.'},source_reference:{state:'unverified',link:null},recorded_at:new Date(Date.UTC(2026,9,6-((i*5)%27),9+(i%8))).toISOString(),writer_seen_count:1+(i%4)}));
 const labels=['Gentler mornings','Focus and recovery','Room to breathe','Tuesday crunch','Family first on weekends','Travel rhythm','Inbox in batches'];
 const groups=[[0,1,25,21],[1,6,10,15],[3,7,17,12],[2,6,12,13],[8,19,22],[18,23,24],[16,13,4]];
 const nodes=labels.map((label,i)=>({id:`synthetic-owner:node:${i+1}`,type:'interpretation',local_id:i+1,label,summary:'A tentative interpretation from saved support.',domain:'day',stored_status:i===2?'stale':'active',recorded_active_at:new Date(Date.UTC(2026,9,5-i)).toISOString(),estimate:.4,estimate_kind:'uncalibrated_model_estimate',support:{claim_ids:groups[i].map(k=>claims[k].id),unavailable_count:0,independent_observations:'unverified'}}));
 const view=params.get('view'),id=params.get('id');
 if(view==='claims'||view==='interpretations') {const rows=view==='claims'?claims:nodes,start=params.get('cursor')?25:0,items=rows.slice(start,start+25);return {...header,view,items,page:{limit:25,returned:items.length,total:rows.length,next_cursor:rows.length>start+25?'synthetic-page-2':null}};}
 if(view==='detail') {const item=claims.find(c=>c.id===id)??nodes.find(n=>n.id===id);if(!item)return {error:'not_found'};return 'text' in item?{...header,view,kind:'claim',item,linked_interpretation_ids:[nodes[0].id]}:{...header,view,kind:'interpretation',item,support_claim_ids:item.support.claim_ids,support_unavailable_count:0};}
 const center=nodes.find(n=>n.id===id);if(!center)return {error:'not_found'};const neighbors=nodes.filter(n=>n.id!==id),start=params.get('cursor')?12:0,shown=neighbors.slice(start,start+12),links=shown.map(n=>({from:id,to:n.id,relation:'possible support',state:'unverified_association',estimate:.3}));
 return {...header,view:'pattern',center,nodes:shown,associations:links,showing:{nodes:shown.length,of_nodes:neighbors.length,links:links.length,of_links:neighbors.length},truncated:neighbors.length>start+12,omitted_links:Math.max(0,neighbors.length-start-12),expand:{next_cursor:neighbors.length>start+12?'synthetic-pattern-2':null,links_capped:false,capped_links_recoverable:false,capped_links:0}};
}
